import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/providers/ThemeProvider';
import Navbar from '@/components/Navbar';
import NextTopLoader from 'nextjs-toploader';
import { Toaster } from '@/components/ui/toaster';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Muhammad Dariaz Zidane',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  icons: {
    apple: '/icon-144.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextTopLoader />
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar />
          <main className="max-w-5xl w-full mx-auto px-5 ">
            {children}
            <Toaster />
          </main>
          <div className="mx-auto ma-w-3xl mt-16 text-center">
            <h1 className=" font-semibold text-primary">Zidane</h1>
            <p className="text-sm my-3">
              © All rights reserved by
              <span className="text-blue-600"> Muhammad Dariaz Zidane</span>
            </p>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
